import React, { useState } from "react";
import {
  Modal,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  Alert,
} from "react-native";
import { EventType, EventStatus } from "../../../types";
import { FirebaseService } from "../../../services/firebase/FirebaseService";
import { createEventModalStyles } from "./CreateEventModal.styles";

interface CreateEventModalProps {
  isVisible: boolean;
  onClose: () => void;
  onEventCreated: (eventId: string) => void;
  initialLocation?: {
    latitude: number;
    longitude: number;
    address?: string;
  };
}

interface EventFormData {
  title: string;
  description: string;
  type: EventType;
  status: EventStatus;
  location: {
    latitude: number;
    longitude: number;
    address: string;
    venue: string;
  };
  startDate: string;
  endDate: string;
  maxParticipants: number;
  organizerName: string;
  tags: string;
  imageUrl: string;
  rewardCoins: number;
  rewardExperience: number;
  rewardBadges: string;
  visibility: "public" | "private" | "friends";
  arModelUrl: string;
  minLevel: number;
  requiredItems: string;
}

const initialFormData: EventFormData = {
  title: "",
  description: "",
  type: "treasure-hunt",
  status: "upcoming",
  location: {
    latitude: 0,
    longitude: 0,
    address: "",
    venue: "",
  },
  startDate: "",
  endDate: "",
  maxParticipants: 100,
  organizerName: "",
  tags: "",
  imageUrl: "",
  rewardCoins: 100,
  rewardExperience: 50,
  rewardBadges: "",
  visibility: "public",
  arModelUrl: "",
  minLevel: 1,
  requiredItems: "",
};

export const CreateEventModal: React.FC<CreateEventModalProps> = ({
  isVisible,
  onClose,
  onEventCreated,
  initialLocation,
}) => {
  const [formData, setFormData] = useState<EventFormData>({
    ...initialFormData,
    location: initialLocation
      ? {
          ...initialFormData.location,
          latitude: initialLocation.latitude,
          longitude: initialLocation.longitude,
          address: initialLocation.address || "",
        }
      : initialFormData.location,
  });
  const [isLoading, setIsLoading] = useState(false);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);

  const eventTypes: EventType[] = [
    "treasure-hunt",
    "ar-experience",
    "community-event",
    "challenge",
    "exhibition",
    "workshop",
    "social",
  ];

  const eventStatuses: EventStatus[] = [
    "upcoming",
    "active",
    "completed",
    "cancelled",
  ];

  const handleInputChange = (field: keyof EventFormData, value: any) => {
    if (field === "location") {
      setFormData((prev) => ({
        ...prev,
        location: { ...prev.location, ...value },
      }));
    } else {
      setFormData((prev) => ({ ...prev, [field]: value }));
    }
  };

  const validateForm = (): boolean => {
    if (!formData.title.trim()) {
      Alert.alert("Validation Error", "Event title is required");
      return false;
    }
    if (!formData.description.trim()) {
      Alert.alert("Validation Error", "Event description is required");
      return false;
    }
    if (!formData.startDate) {
      Alert.alert("Validation Error", "Start date is required");
      return false;
    }
    if (!formData.endDate) {
      Alert.alert("Validation Error", "End date is required");
      return false;
    }
    if (new Date(formData.startDate) >= new Date(formData.endDate)) {
      Alert.alert("Validation Error", "End date must be after start date");
      return false;
    }
    if (!formData.organizerName.trim()) {
      Alert.alert("Validation Error", "Organizer name is required");
      return false;
    }
    if (formData.location.latitude === 0 && formData.location.longitude === 0) {
      Alert.alert("Validation Error", "Event location is required");
      return false;
    }
    return true;
  };

  const handleSubmit = async () => {
    if (!validateForm()) return;

    setIsLoading(true);

    try {
      const eventData = {
        id: "", // Will be generated by Firebase
        title: formData.title.trim(),
        description: formData.description.trim(),
        type: formData.type,
        status: formData.status,
        location: {
          latitude: formData.location.latitude,
          longitude: formData.location.longitude,
          address: formData.location.address.trim(),
          venue: formData.location.venue.trim(),
        },
        startDate: formData.startDate,
        endDate: formData.endDate,
        maxParticipants: formData.maxParticipants,
        currentParticipants: 0,
        participants: [],
        organizer: {
          id: "current_user", // TODO: Get from auth context
          name: formData.organizerName.trim(),
        },
        tags: formData.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter((tag) => tag.length > 0),
        image: formData.imageUrl.trim() || undefined,
        arContent: formData.arModelUrl.trim()
          ? {
              model: formData.arModelUrl.trim(),
              animations: [],
              textures: [],
            }
          : undefined,
        rewards: {
          coins: formData.rewardCoins,
          experience: formData.rewardExperience,
          badges: formData.rewardBadges
            .split(",")
            .map((badge) => badge.trim())
            .filter((badge) => badge.length > 0),
        },
        requirements: {
          minLevel: formData.minLevel,
          items: formData.requiredItems
            .split(",")
            .map((item) => item.trim())
            .filter((item) => item.length > 0),
        },
        visibility: formData.visibility,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      const eventId = await FirebaseService.createEvent(eventData);

      Alert.alert("Success", "Event created successfully!", [
        {
          text: "OK",
          onPress: () => {
            setFormData(initialFormData);
            onEventCreated(eventId);
            onClose();
          },
        },
      ]);
    } catch (error) {
      console.error("Error creating event:", error);
      Alert.alert("Error", "Failed to create event. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const handleClose = () => {
    setFormData(initialFormData);
    onClose();
  };

  return (
    <Modal
      visible={isVisible}
      animationType="slide"
      presentationStyle="pageSheet"
    >
      <View style={createEventModalStyles.container}>
        <View style={createEventModalStyles.header}>
          <TouchableOpacity
            onPress={handleClose}
            style={createEventModalStyles.cancelButton}
          >
            <Text style={createEventModalStyles.cancelText}>Cancel</Text>
          </TouchableOpacity>
          <Text style={createEventModalStyles.title}>Create Event</Text>
          <TouchableOpacity
            onPress={handleSubmit}
            style={[
              createEventModalStyles.submitButton,
              isLoading && createEventModalStyles.submitButtonDisabled,
            ]}
            disabled={isLoading}
          >
            <Text style={createEventModalStyles.submitText}>
              {isLoading ? "Creating..." : "Create"}
            </Text>
          </TouchableOpacity>
        </View>

        <ScrollView
          style={createEventModalStyles.content}
          showsVerticalScrollIndicator={false}
        >
          {/* Basic Information */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>
              Basic Information
            </Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Event Title *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.title}
                onChangeText={(text) => handleInputChange("title", text)}
                placeholder="Enter event title"
                placeholderTextColor="#999"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Description *</Text>
              <TextInput
                style={[
                  createEventModalStyles.input,
                  createEventModalStyles.textArea,
                ]}
                value={formData.description}
                onChangeText={(text) => handleInputChange("description", text)}
                placeholder="Describe your event"
                placeholderTextColor="#999"
                multiline
                numberOfLines={4}
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Event Type</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.type
                    .replace("-", " ")
                    .replace(/\b\w/g, (l) => l.toUpperCase())}
                </Text>
              </TouchableOpacity>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Status</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.status.charAt(0).toUpperCase() +
                    formData.status.slice(1)}
                </Text>
              </TouchableOpacity>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Organizer Name *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.organizerName}
                onChangeText={(text) =>
                  handleInputChange("organizerName", text)
                }
                placeholder="Enter organizer name"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Date & Time */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Date & Time</Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Start Date *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.startDate}
                onChangeText={(text) => handleInputChange("startDate", text)}
                placeholder="YYYY-MM-DDTHH:MM:SSZ"
                placeholderTextColor="#999"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>End Date *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.endDate}
                onChangeText={(text) => handleInputChange("endDate", text)}
                placeholder="YYYY-MM-DDTHH:MM:SSZ"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Location */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Location</Text>

            <View style={createEventModalStyles.row}>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginRight: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Latitude</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.location.latitude.toString()}
                  onChangeText={(text) =>
                    handleInputChange("location", {
                      latitude: parseFloat(text) || 0,
                    })
                  }
                  placeholder="0.0"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginLeft: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Longitude</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.location.longitude.toString()}
                  onChangeText={(text) =>
                    handleInputChange("location", {
                      longitude: parseFloat(text) || 0,
                    })
                  }
                  placeholder="0.0"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Address</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.location.address}
                onChangeText={(text) =>
                  handleInputChange("location", { address: text })
                }
                placeholder="Enter address"
                placeholderTextColor="#999"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Venue</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.location.venue}
                onChangeText={(text) =>
                  handleInputChange("location", { venue: text })
                }
                placeholder="Enter venue name"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Participation */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>
              Participation
            </Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Max Participants</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.maxParticipants.toString()}
                onChangeText={(text) =>
                  handleInputChange("maxParticipants", parseInt(text) || 100)
                }
                placeholder="100"
                placeholderTextColor="#999"
                keyboardType="numeric"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Visibility</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.visibility === "public"
                    ? "Public"
                    : formData.visibility === "friends"
                    ? "Friends Only"
                    : "Private"}
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Rewards */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Rewards</Text>

            <View style={createEventModalStyles.row}>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginRight: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Coins</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.rewardCoins.toString()}
                  onChangeText={(text) =>
                    handleInputChange("rewardCoins", parseInt(text) || 0)
                  }
                  placeholder="100"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginLeft: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Experience</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.rewardExperience.toString()}
                  onChangeText={(text) =>
                    handleInputChange("rewardExperience", parseInt(text) || 0)
                  }
                  placeholder="50"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>
                Badges (comma-separated)
              </Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.rewardBadges}
                onChangeText={(text) => handleInputChange("rewardBadges", text)}
                placeholder="First Prize, Second Prize, Third Prize"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Advanced Options */}
          <View style={createEventModalStyles.section}>
            <TouchableOpacity
              style={createEventModalStyles.advancedToggle}
              onPress={() => setShowAdvancedOptions(!showAdvancedOptions)}
            >
              <Text style={createEventModalStyles.sectionTitle}>
                Advanced Options
              </Text>
              <Text style={createEventModalStyles.toggleIcon}>
                {showAdvancedOptions ? "−" : "+"}
              </Text>
            </TouchableOpacity>

            {showAdvancedOptions && (
              <>
                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Tags (comma-separated)
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.tags}
                    onChangeText={(text) => handleInputChange("tags", text)}
                    placeholder="urban, exploration, landmarks"
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>Image URL</Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.imageUrl}
                    onChangeText={(text) => handleInputChange("imageUrl", text)}
                    placeholder="https://..."
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>AR Model URL</Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.arModelUrl}
                    onChangeText={(text) =>
                      handleInputChange("arModelUrl", text)
                    }
                    placeholder="https://..."
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Minimum Level
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.minLevel.toString()}
                    onChangeText={(text) =>
                      handleInputChange("minLevel", parseInt(text) || 1)
                    }
                    placeholder="1"
                    placeholderTextColor="#999"
                    keyboardType="numeric"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Required Items (comma-separated)
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.requiredItems}
                    onChangeText={(text) =>
                      handleInputChange("requiredItems", text)
                    }
                    placeholder="flashlight, map, compass"
                    placeholderTextColor="#999"
                  />
                </View>
              </>
            )}
          </View>

          <View style={createEventModalStyles.bottomSpacing} />
        </ScrollView>
      </View>
    </Modal>
  );
};
