import React, { useState } from "react";
import {
  Modal,
  View,
  Text,
  TextInput,
  TouchableOpacity,
  ScrollView,
  Alert,
} from "react-native";
import DateTimePicker from "@react-native-community/datetimepicker";
import { EventType, EventStatus } from "../../../types";
import { FirebaseService } from "../../../services/firebase/FirebaseService";
import { isAdmin } from "../../../utils/userRoles";
import { createEventModalStyles } from "./CreateEventModal.styles";

interface CreateEventModalProps {
  isVisible: boolean;
  onClose: () => void;
  onEventCreated: (eventId: string) => void;
  initialLocation?: {
    latitude: number;
    longitude: number;
    address?: string;
  };
}

interface EventFormData {
  title: string;
  description: string;
  type: EventType;
  status: EventStatus;
  location: {
    latitude: number;
    longitude: number;
    address: string;
    venue: string;
  };
  startDate: Date;
  endDate: Date;
  maxParticipants: number;
  organizerName: string;
  tags: string;
  imageUrl: string;
  rewardCoins: number;
  rewardExperience: number;
  rewardBadges: string;
  visibility: "public" | "private" | "friends";
  arModelUrl: string;
  minLevel: number;
  requiredItems: string;
  // Hunt-specific fields
  huntDifficulty: "Easy" | "Medium" | "Hard";
  huntTerrain:
    | "Urban"
    | "Forest"
    | "Beach"
    | "Mountain"
    | "Desert"
    | "Park"
    | "Historical";
  huntRange: number;
  // Admin-specific fields
  coinCount: number;
  centerCoins: number;
}

const initialFormData: EventFormData = {
  title: "",
  description: "",
  type: "treasure-hunt",
  status: "upcoming",
  location: {
    latitude: 0,
    longitude: 0,
    address: "",
    venue: "",
  },
  startDate: new Date(),
  endDate: new Date(Date.now() + 3600000), // 1 hour later
  maxParticipants: 100,
  organizerName: "",
  tags: "",
  imageUrl: "",
  rewardCoins: 100,
  rewardExperience: 50,
  rewardBadges: "",
  visibility: "public",
  arModelUrl: "",
  minLevel: 1,
  requiredItems: "",
  // Hunt-specific initial values
  huntDifficulty: "Medium",
  huntTerrain: "Urban",
  huntRange: 2,
  // Admin-specific initial values
  coinCount: 20,
  centerCoins: 5,
};

export const CreateEventModal: React.FC<CreateEventModalProps> = ({
  isVisible,
  onClose,
  onEventCreated,
  initialLocation,
}) => {
  const [formData, setFormData] = useState<EventFormData>({
    ...initialFormData,
    location: initialLocation
      ? {
          ...initialFormData.location,
          latitude: initialLocation.latitude,
          longitude: initialLocation.longitude,
          address: initialLocation.address || "",
        }
      : initialFormData.location,
  });
  const [isLoading, setIsLoading] = useState(false);
  const [showAdvancedOptions, setShowAdvancedOptions] = useState(false);
  const [showStartDatePicker, setShowStartDatePicker] = useState(false);
  const [showEndDatePicker, setShowEndDatePicker] = useState(false);
  const [startDateMode, _setStartDateMode] = useState<"date" | "time">("date");
  const [endDateMode, _setEndDateMode] = useState<"date" | "time">("date");

  const handleInputChange = (field: keyof EventFormData, value: any) => {
    if (field === "location") {
      setFormData((prev) => ({
        ...prev,
        location: { ...prev.location, ...value },
      }));
    } else {
      setFormData((prev) => ({ ...prev, [field]: value }));
    }
  };

  const validateForm = (): boolean => {
    if (!formData.title.trim()) {
      Alert.alert("Validation Error", "Event title is required");
      return false;
    }
    if (!formData.description.trim()) {
      Alert.alert("Validation Error", "Event description is required");
      return false;
    }
    if (!formData.startDate) {
      Alert.alert("Validation Error", "Start date is required");
      return false;
    }
    if (!formData.endDate) {
      Alert.alert("Validation Error", "End date is required");
      return false;
    }
    if (formData.startDate >= formData.endDate) {
      Alert.alert("Validation Error", "End date must be after start date");
      return false;
    }
    if (!formData.organizerName.trim()) {
      Alert.alert("Validation Error", "Organizer name is required");
      return false;
    }
    if (formData.location.latitude === 0 && formData.location.longitude === 0) {
      Alert.alert("Validation Error", "Event location is required");
      return false;
    }
    return true;
  };

  const handleSubmit = async () => {
    if (!validateForm()) {
      return;
    }

    setIsLoading(true);

    try {
      const eventData = {
        id: "", // Will be generated by Firebase
        title: formData.title.trim(),
        description: formData.description.trim(),
        type: formData.type,
        status: formData.status,
        location: {
          latitude: formData.location.latitude,
          longitude: formData.location.longitude,
          address: formData.location.address.trim(),
          venue: formData.location.venue.trim(),
        },
        startDate: formData.startDate.toISOString(),
        endDate: formData.endDate.toISOString(),
        maxParticipants: formData.maxParticipants,
        currentParticipants: 0,
        participants: [],
        organizer: {
          id: "current_user", // TODO: Get from auth context
          name: formData.organizerName.trim(),
        },
        tags: formData.tags
          .split(",")
          .map((tag) => tag.trim())
          .filter((tag) => tag.length > 0),
        image: formData.imageUrl.trim() || undefined,
        arContent: formData.arModelUrl.trim()
          ? {
              model: formData.arModelUrl.trim(),
              animations: [],
              textures: [],
            }
          : undefined,
        rewards: {
          coins: formData.rewardCoins,
          experience: formData.rewardExperience,
          badges: formData.rewardBadges
            .split(",")
            .map((badge) => badge.trim())
            .filter((badge) => badge.length > 0),
        },
        requirements: {
          minLevel: formData.minLevel,
          items: formData.requiredItems
            .split(",")
            .map((item) => item.trim())
            .filter((item) => item.length > 0),
        },
        visibility: formData.visibility,
        huntDetails: {
          difficulty: formData.huntDifficulty,
          terrain: formData.huntTerrain,
          range: formData.huntRange,
          totalPrizePool: formData.rewardCoins + formData.rewardExperience * 2,
          huntType: (formData.huntDifficulty === "Easy"
            ? "Flash Hunt"
            : formData.huntDifficulty === "Hard"
            ? "Epic Journey Hunt"
            : "Adventure Hunt") as
            | "Flash Hunt"
            | "Epic Journey Hunt"
            | "Adventure Hunt",
        },
        // Legacy fields for backward compatibility
        terrain: formData.huntTerrain,
        difficulty: formData.huntDifficulty,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      };

      const eventId = await FirebaseService.createEvent(eventData);

      // Auto-create coins for the event
      console.log("[CreateEvent] Creating coins for new event:", eventId);
      await createCoinsForEvent(eventId, formData.location);

      Alert.alert("Success", "Event created successfully with coins!", [
        {
          text: "OK",
          onPress: () => {
            setFormData(initialFormData);
            onEventCreated(eventId);
            onClose();
          },
        },
      ]);
    } catch (error) {
      console.error("Error creating event:", error);
      Alert.alert("Error", "Failed to create event. Please try again.");
    } finally {
      setIsLoading(false);
    }
  };

  const createCoinsForEvent = async (
    eventId: string,
    centerLocation: { latitude: number; longitude: number }
  ) => {
    const currentUser = FirebaseService.getCurrentUser?.();
    const userIsAdmin = isAdmin(currentUser?.email || null);

    const centerCoinsCount = userIsAdmin ? formData.centerCoins : 5;
    const totalCoinsCount = userIsAdmin ? formData.coinCount : 20;
    try {
      const { latitude: centerLat, longitude: centerLon } = centerLocation;

      // Calculate meters per degree for this location
      const metersPerDegLat = 111320;
      const metersPerDegLon = 111320 * Math.cos((centerLat * Math.PI) / 180);

      const coinPromises = [];

      // Create center coins (within 100m)
      for (let i = 0; i < centerCoinsCount; i++) {
        const distance = Math.random() * 100 + 20; // 20-120 meters from center
        const angle = Math.random() * 2 * Math.PI;

        const offsetLat = (distance * Math.cos(angle)) / metersPerDegLat;
        const offsetLon = (distance * Math.sin(angle)) / metersPerDegLon;

        const coinData = {
          eventId,
          location: {
            latitude: centerLat + offsetLat,
            longitude: centerLon + offsetLon,
          },
          collectible: true,
          collected: false,
          value: Math.floor(Math.random() * 50) + 25, // 25-74 points
          rarity: ["common", "uncommon", "rare"][Math.floor(Math.random() * 3)],
          name: `Center Coin ${i + 1}`,
          metadata: {
            source: "event-creation-center",
            distance: distance.toFixed(1),
            angle: ((angle * 180) / Math.PI).toFixed(1),
          },
        };

        coinPromises.push(FirebaseService.createCoin(coinData));
      }

      // Create distributed coins in 4km radius
      const distributedCoinsCount = Math.max(
        0,
        totalCoinsCount - centerCoinsCount
      );
      for (let i = 0; i < distributedCoinsCount; i++) {
        const distance = Math.random() * 3800 + 200; // 200m-4km from center
        const angle = Math.random() * 2 * Math.PI;

        const offsetLat = (distance * Math.cos(angle)) / metersPerDegLat;
        const offsetLon = (distance * Math.sin(angle)) / metersPerDegLon;

        const coinData = {
          eventId,
          location: {
            latitude: centerLat + offsetLat,
            longitude: centerLon + offsetLon,
          },
          collectible: true,
          collected: false,
          value: Math.floor(Math.random() * 100) + 10, // 10-109 points
          rarity: ["common", "uncommon", "rare", "epic"][
            Math.floor(Math.random() * 4)
          ],
          name: `Hunt Coin ${i + 1}`,
          metadata: {
            source: "event-creation-distributed",
            distance: distance.toFixed(1),
            angle: ((angle * 180) / Math.PI).toFixed(1),
          },
        };

        coinPromises.push(FirebaseService.createCoin(coinData));
      }

      console.log(
        `[CreateEvent] Creating ${coinPromises.length} coins for event ${eventId}`
      );
      await Promise.all(coinPromises);
      console.log(
        `[CreateEvent] Successfully created ${coinPromises.length} coins`
      );
    } catch (error) {
      console.error("Error creating coins for event:", error);
      // Don't throw - event creation succeeded, coin creation is bonus
    }
  };

  const handleClose = () => {
    setFormData(initialFormData);
    onClose();
  };

  return (
    <Modal
      visible={isVisible}
      animationType="slide"
      presentationStyle="pageSheet"
    >
      <View style={createEventModalStyles.container}>
        <View style={createEventModalStyles.header}>
          <TouchableOpacity
            onPress={handleClose}
            style={createEventModalStyles.cancelButton}
          >
            <Text style={createEventModalStyles.cancelText}>Cancel</Text>
          </TouchableOpacity>
          <Text style={createEventModalStyles.title}>Create Event</Text>
          <TouchableOpacity
            onPress={handleSubmit}
            style={[
              createEventModalStyles.submitButton,
              isLoading && createEventModalStyles.submitButtonDisabled,
            ]}
            disabled={isLoading}
          >
            <Text style={createEventModalStyles.submitText}>
              {isLoading ? "Creating..." : "Create"}
            </Text>
          </TouchableOpacity>
        </View>

        <ScrollView
          style={createEventModalStyles.content}
          showsVerticalScrollIndicator={false}
        >
          {/* Basic Information */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>
              Basic Information
            </Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Event Title *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.title}
                onChangeText={(text) => handleInputChange("title", text)}
                placeholder="Enter event title"
                placeholderTextColor="#999"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Description *</Text>
              <TextInput
                style={[
                  createEventModalStyles.input,
                  createEventModalStyles.textArea,
                ]}
                value={formData.description}
                onChangeText={(text) => handleInputChange("description", text)}
                placeholder="Describe your event"
                placeholderTextColor="#999"
                multiline
                numberOfLines={4}
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Event Type</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.type
                    .replace("-", " ")
                    .replace(/\b\w/g, (l) => l.toUpperCase())}
                </Text>
              </TouchableOpacity>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Status</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.status.charAt(0).toUpperCase() +
                    formData.status.slice(1)}
                </Text>
              </TouchableOpacity>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Organizer Name *</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.organizerName}
                onChangeText={(text) =>
                  handleInputChange("organizerName", text)
                }
                placeholder="Enter organizer name"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Date & Time */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Date & Time</Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Start Date *</Text>
              <TouchableOpacity
                style={createEventModalStyles.input}
                onPress={() => setShowStartDatePicker(true)}
              >
                <Text style={createEventModalStyles.dateText}>
                  {formData.startDate.toLocaleDateString()}{" "}
                  {formData.startDate.toLocaleTimeString()}
                </Text>
              </TouchableOpacity>
              {showStartDatePicker && (
                <DateTimePicker
                  value={formData.startDate}
                  mode={startDateMode}
                  display="default"
                  onChange={(event, selectedDate) => {
                    setShowStartDatePicker(false);
                    if (selectedDate) {
                      handleInputChange("startDate", selectedDate);
                    }
                  }}
                />
              )}
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>End Date *</Text>
              <TouchableOpacity
                style={createEventModalStyles.input}
                onPress={() => setShowEndDatePicker(true)}
              >
                <Text style={createEventModalStyles.dateText}>
                  {formData.endDate.toLocaleDateString()}{" "}
                  {formData.endDate.toLocaleTimeString()}
                </Text>
              </TouchableOpacity>
              {showEndDatePicker && (
                <DateTimePicker
                  value={formData.endDate}
                  mode={endDateMode}
                  display="default"
                  onChange={(event, selectedDate) => {
                    setShowEndDatePicker(false);
                    if (selectedDate) {
                      handleInputChange("endDate", selectedDate);
                    }
                  }}
                />
              )}
            </View>
          </View>

          {/* Location */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Location</Text>

            <View style={createEventModalStyles.row}>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginRight: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Latitude</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.location.latitude.toString()}
                  onChangeText={(text) =>
                    handleInputChange("location", {
                      latitude: parseFloat(text) || 0,
                    })
                  }
                  placeholder="0.0"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginLeft: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Longitude</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.location.longitude.toString()}
                  onChangeText={(text) =>
                    handleInputChange("location", {
                      longitude: parseFloat(text) || 0,
                    })
                  }
                  placeholder="0.0"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
            </View>

            <TouchableOpacity
              style={[
                createEventModalStyles.input,
                createEventModalStyles.mapButton,
              ]}
              onPress={() => {
                Alert.alert(
                  "Choose Location",
                  "This feature will open a map to let you pick a location by tapping. For now, please enter coordinates manually.",
                  [{ text: "OK" }]
                );
                // TODO: Implement map picker
                // This should open a map modal where user can tap to select location
                // and it auto-fills the latitude/longitude fields
              }}
            >
              <Text style={createEventModalStyles.mapButtonText}>
                📍 Choose on Map
              </Text>
            </TouchableOpacity>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Address</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.location.address}
                onChangeText={(text) =>
                  handleInputChange("location", { address: text })
                }
                placeholder="Enter address"
                placeholderTextColor="#999"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Venue</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.location.venue}
                onChangeText={(text) =>
                  handleInputChange("location", { venue: text })
                }
                placeholder="Enter venue name"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Participation */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>
              Participation
            </Text>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Max Participants</Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.maxParticipants.toString()}
                onChangeText={(text) =>
                  handleInputChange(
                    "maxParticipants",
                    parseInt(text, 10) || 100
                  )
                }
                placeholder="100"
                placeholderTextColor="#999"
                keyboardType="numeric"
              />
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>Visibility</Text>
              <TouchableOpacity style={createEventModalStyles.input}>
                <Text style={createEventModalStyles.pickerText}>
                  {formData.visibility === "public"
                    ? "Public"
                    : formData.visibility === "friends"
                    ? "Friends Only"
                    : "Private"}
                </Text>
              </TouchableOpacity>
            </View>
          </View>

          {/* Rewards */}
          <View style={createEventModalStyles.section}>
            <Text style={createEventModalStyles.sectionTitle}>Rewards</Text>

            <View style={createEventModalStyles.row}>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginRight: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Coins</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.rewardCoins.toString()}
                  onChangeText={(text) =>
                    handleInputChange("rewardCoins", parseInt(text, 10) || 0)
                  }
                  placeholder="100"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
              <View
                style={[
                  createEventModalStyles.inputGroup,
                  { flex: 1, marginLeft: 8 },
                ]}
              >
                <Text style={createEventModalStyles.label}>Experience</Text>
                <TextInput
                  style={createEventModalStyles.input}
                  value={formData.rewardExperience.toString()}
                  onChangeText={(text) =>
                    handleInputChange(
                      "rewardExperience",
                      parseInt(text, 10) || 0
                    )
                  }
                  placeholder="50"
                  placeholderTextColor="#999"
                  keyboardType="numeric"
                />
              </View>
            </View>

            <View style={createEventModalStyles.inputGroup}>
              <Text style={createEventModalStyles.label}>
                Badges (comma-separated)
              </Text>
              <TextInput
                style={createEventModalStyles.input}
                value={formData.rewardBadges}
                onChangeText={(text) => handleInputChange("rewardBadges", text)}
                placeholder="First Prize, Second Prize, Third Prize"
                placeholderTextColor="#999"
              />
            </View>
          </View>

          {/* Advanced Options */}
          <View style={createEventModalStyles.section}>
            <TouchableOpacity
              style={createEventModalStyles.advancedToggle}
              onPress={() => setShowAdvancedOptions(!showAdvancedOptions)}
            >
              <Text style={createEventModalStyles.sectionTitle}>
                Advanced Options
              </Text>
              <Text style={createEventModalStyles.toggleIcon}>
                {showAdvancedOptions ? "−" : "+"}
              </Text>
            </TouchableOpacity>

            {showAdvancedOptions && (
              <>
                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Tags (comma-separated)
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.tags}
                    onChangeText={(text) => handleInputChange("tags", text)}
                    placeholder="urban, exploration, landmarks"
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>Image URL</Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.imageUrl}
                    onChangeText={(text) => handleInputChange("imageUrl", text)}
                    placeholder="https://..."
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>AR Model URL</Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.arModelUrl}
                    onChangeText={(text) =>
                      handleInputChange("arModelUrl", text)
                    }
                    placeholder="https://..."
                    placeholderTextColor="#999"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Minimum Level
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.minLevel.toString()}
                    onChangeText={(text) =>
                      handleInputChange("minLevel", parseInt(text, 10) || 1)
                    }
                    placeholder="1"
                    placeholderTextColor="#999"
                    keyboardType="numeric"
                  />
                </View>

                <View style={createEventModalStyles.inputGroup}>
                  <Text style={createEventModalStyles.label}>
                    Required Items (comma-separated)
                  </Text>
                  <TextInput
                    style={createEventModalStyles.input}
                    value={formData.requiredItems}
                    onChangeText={(text) =>
                      handleInputChange("requiredItems", text)
                    }
                    placeholder="flashlight, map, compass"
                    placeholderTextColor="#999"
                  />
                </View>

                {/* Admin-only coin configuration */}
                {(() => {
                  const currentUser = FirebaseService.getCurrentUser?.();
                  const userIsAdmin = isAdmin(currentUser?.email || null);
                  return userIsAdmin ? (
                    <>
                      <View style={createEventModalStyles.inputGroup}>
                        <Text style={createEventModalStyles.label}>
                          🪙 Coin Configuration (Admin)
                        </Text>
                      </View>

                      <View style={createEventModalStyles.row}>
                        <View
                          style={[
                            createEventModalStyles.inputGroup,
                            { flex: 1, marginRight: 8 },
                          ]}
                        >
                          <Text style={createEventModalStyles.label}>
                            Total Coins
                          </Text>
                          <TextInput
                            style={createEventModalStyles.input}
                            value={formData.coinCount.toString()}
                            onChangeText={(text) =>
                              handleInputChange(
                                "coinCount",
                                parseInt(text, 10) || 20
                              )
                            }
                            placeholder="20"
                            placeholderTextColor="#999"
                            keyboardType="numeric"
                          />
                        </View>
                        <View
                          style={[
                            createEventModalStyles.inputGroup,
                            { flex: 1, marginLeft: 8 },
                          ]}
                        >
                          <Text style={createEventModalStyles.label}>
                            Center Coins
                          </Text>
                          <TextInput
                            style={createEventModalStyles.input}
                            value={formData.centerCoins.toString()}
                            onChangeText={(text) =>
                              handleInputChange(
                                "centerCoins",
                                parseInt(text, 10) || 5
                              )
                            }
                            placeholder="5"
                            placeholderTextColor="#999"
                            keyboardType="numeric"
                          />
                        </View>
                      </View>
                    </>
                  ) : null;
                })()}
              </>
            )}
          </View>

          <View style={createEventModalStyles.bottomSpacing} />
        </ScrollView>
      </View>
    </Modal>
  );
};
