import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#121212",
  },
  scrollContainer: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  header: {
    alignItems: "center",
    marginBottom: 30,
  },
  profileImageContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: "#7B3FE4",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    shadowColor: "#7B3FE4",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
  },
  profileImagePlaceholder: {
    fontSize: 40,
    color: "#FFFFFF",
    fontWeight: "bold",
  },
  userName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  userEmail: {
    fontSize: 16,
    color: "#B0B0B0",
    marginBottom: 8,
  },
  userLevel: {
    fontSize: 14,
    color: "#7B3FE4",
    fontWeight: "600",
    backgroundColor: "rgba(123, 63, 228, 0.2)",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
    overflow: "hidden",
  },
  statsContainer: {
    marginBottom: 30,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  statsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  statCard: {
    width: "48%",
    backgroundColor: "#1E1E1E",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#333333",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#7B3FE4",
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 14,
    color: "#B0B0B0",
  },
  achievementsContainer: {
    marginBottom: 30,
  },
  achievementsList: {
    gap: 12,
  },
  achievementCard: {
    backgroundColor: "#1E1E1E",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "#333333",
    flexDirection: "row",
    alignItems: "center",
  },
  achievementIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "#7B3FE4",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  achievementIconText: {
    fontSize: 20,
    color: "#FFFFFF",
  },
  achievementInfo: {
    flex: 1,
  },
  achievementName: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 2,
  },
  achievementDescription: {
    fontSize: 14,
    color: "#B0B0B0",
  },
  progressBarContainer: {
    marginTop: 8,
  },
  progressBarBackground: {
    height: 6,
    backgroundColor: "#333333",
    borderRadius: 3,
  },
  progressBarFill: {
    height: 6,
    backgroundColor: "#7B3FE4",
    borderRadius: 3,
  },
  progressText: {
    fontSize: 12,
    color: "#B0B0B0",
    marginTop: 4,
    textAlign: "right",
  },
  settingsContainer: {
    marginBottom: 20,
  },
  settingItem: {
    backgroundColor: "#1E1E1E",
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: "#333333",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  settingLeft: {
    flexDirection: "row",
    alignItems: "center",
    flex: 1,
  },
  settingIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: "#7B3FE4",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  settingIconText: {
    fontSize: 16,
    color: "#FFFFFF",
  },
  settingText: {
    fontSize: 16,
    color: "#FFFFFF",
    fontWeight: "500",
  },
  settingArrow: {
    fontSize: 18,
    color: "#B0B0B0",
  },
  logoutButton: {
    backgroundColor: "#FF4444",
    borderRadius: 12,
    padding: 16,
    alignItems: "center",
    marginTop: 20,
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#FFFFFF",
  },
});
